[jtbc_factcheck]
title = "JTBC 뉴스 ─ 팩트체크"
url = "https://news.jtbc.joins.com/factcheck/"
entrySelector = "div.bd.news_area ul li"
titleSelector = "div.news dl dt"
linkSelector = "div.news dl dt a"
contentSelector = "dl dd.desc a"
imageSelector = "div.news dl dd a img"
waitForSelector = "div.bd.news_area ul li"

[kbsnews_factcheck]
title = "KBS뉴스 ─ 팩트체크K"
url = "https://news.kbs.co.kr/news/list.do?mcd=1032"
entrySelector = "ul.list-type.list-thumb li"
titleSelector = "em.tit"
linkSelector = "a"
contentSelector = "span.script"
imageSelector = "span.img-center img"
waitUntil = "networkidle"

[sbsnews_fact]
title = "SBS뉴스 ─ 사실은"
url = "https://news.sbs.co.kr/news/fact.do"
entrySelector = "ul.type_thumb li"
titleSelector = "strong"
linkSelector = "a"
imageSelector = "span.thumb img"
contentSelector = "a.reporter"
waitUntil = "networkidle"

[mbcnews_turnedout]
title = "MBC뉴스 ─ 알고보니"
url = "https://news.imbc.com/newszoomin/turnedout/"
entrySelector = "ul.thumb_type.list_thumb_c li.item"
titleSelector = "span[class^='tit ellipsis']"
linkSelector = "a"
imageSelector = "span.img.ico_vod img"
contentSelector = "span.sub2"
waitUntil = "networkidle"

[yna_factcheck]
title = "연합뉴스 ─ 팩트체크"
url = "https://www.yna.co.kr/theme-list/factcheck?site=navi_factcheck"
entrySelector = "div.list-type038 ul.list li"
titleSelector = "strong.tit-news"
linkSelector = "div.news-con a"
contentSelector = "p.lead"
imageSelector = "figure.img-con img"
waitUntil = "networkidle"

[dongascience_factcheck]
title = "동아사이언스 ─ 팩트체크"
url = "https://www.dongascience.com/special.php?category=001_148"
entrySelector = "div.article-A2 ul li"
titleSelector = "span.tit"
linkSelector = "a"
contentSelector = "span.cont div.two-lines"
waitUntil = "networkidle"

[khan_factcheck]
title = "경향신문 ─ 연재 ─ 팩트체크"
url = "https://www.khan.co.kr/series/articles/aj165"
entrySelector = "div.main-list-wrap ul.df-list li"
titleSelector = "h2.tit a"
linkSelector = "h2.tit a"
contentSelector = "span.lead a.line_clamp2"
dateSelector = "span.byline"
dateFormat = "yyyy.MM.dd hh:mm"
imageSelector = "div.thumb picture img"
waitUntil = "networkidle"

[ohmynews_ohmyfact]
title = "오마이뉴스 ─ 오마이팩트"
url = "http://www.ohmynews.com/NWS_Web/OhmyFact/index.aspx"
entrySelector = "div.newest_box ul.newest_list.main li.list-wrp"
titleSelector = "div.newest_area a.link_today div.text_area strong.title"
linkSelector = "div.newest_area a.link_today"
contentSelector = "div.newest_area a.link_today div.text_area p.sbtit"
imageSelector = "div.verify-box span.face"
waitUntil = "networkidle"

[hani_factcheck]
title = "한겨레 ─ 팩트체크"
url = "https://www.hani.co.kr/arti/SERIES/1459/title1.html"
entrySelector = "div.series-list-area ul.one-type li"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
